# Welcome to Jekyll!
#
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: СПБГУГА Группа 834
favicon: "Jet_favicon.png"
# email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/834/wiki" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username:  jekyll


#Collections
collections:
  Aviation-English:
    output: true
    permalink: /Aviation-English/:path/
    cyrillic: Авиационный Английский
    status: taught

  BZhD:
    output: true
    permalink: /BZhD/:path/
    status: taught
    cyrillic: БЖД

  BIUS:
    output: true
    permalink: /BIUS/:path/
    status: taught
    cyrillic: БИУС

  Konstruktsiya-AD:
    output: true
    permalink: /Konstruktsiya-AD/:path/
    status: taught
    cyrillic: Конструкция и Прочность АД

  Metodi-Diagnostiki:
    output: true
    permalink: /Metodi-Diagnostiki/:path/
    status: taught
    cyrillic: Методы Современных Диагностики

  Teoriya-AD:
    output: true
    permalink: /Teoriya-AD/:path/
    status: taught
    cyrillic: Теория АД

  Teoriya-Nadezhnosti:
    output: true
    permalink: /Teoriya-Nadezhnosti/:path/
    status: taught
    cyrillic: Теория Надежности

  Fiz-Ra:
    output: true
    permalink: /Fiz-Ra/:path/
    status: taught
    cyrillic: Физ-Ра

# Build settings
markdown: kramdown
theme: minima
